import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./comp/navbar";
import Footer from "./comp/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black bg-gradient-to-br from-gray-900 via-black to-purple-900">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
